services:
  jenkins:
    image: ci-pipeline-lab-jenkins
    container_name: ci-pipeline-lab-jenkins
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
