services:
  jenkins:
    image: ci-pipeline-lab-jenkins
    container_name: ci-pipeline-lab-jenkins
    ports:
      - '8080:8080'
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc/jenkins.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./docker/jenkins/casc:/var/jenkins_home/casc

volumes:
  jenkins_home:
